env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules: 
  prefer-const: off
  no-prototype-builtins: off
  no-debugger: warn
  no-unused-vars: off
  no-mixed-spaces-and-tabs: warn
  jsx-quotes:
    - error
    - prefer-single
  quotes: 
    - error
    - single
  '@typescript-eslint/no-empty-interface': warn
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/ban-ts-comment': warn
  '@typescript-eslint/consistent-type-imports': error
  "@typescript-eslint/no-inferrable-types": warn
  'react/prop-types': warn
  '@typescript-eslint/no-this-alias':
    - off # temp
    - 
      allowDestructuring: false
      allowedNames: 
        - self
  semi:
    - warn
    - always
