env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: 
  prefer-const: off
  no-prototype-builtins: off
  '@typescript-eslint/no-empty-interface': warn
  '@typescript-eslint/ban-ts-comment': warn
  semi:
    - error
    - always
